remote_theme: "mmistakes/minimal-mistakes"
title: "Varlink"
og_image: /images/varlink.png
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      sidebar:
        nav: "docs"




